version = 0.1

[default.deploy.parameters]
stack_name = "gemini-api"
resolve_s3 = false                  # does not create new bucket
s3_bucket = "wits-sam-deployments"
s3_prefix = "gemini-api"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
